# try :
#     print(a)
# except Exception as e:
#     print(e)
# finally:
#     print ("this is finally blocked")
# print ("hello world")

# def add(x,y):

#     return x+y
# try:
#     print(add(10,20))
# except Exception as e:
#     print (e)


